version: '2.0'

services:
  quiz-db:
    container_name: quiz-db
    restart: always
    build:
      context: .
      dockerfile: ./quiz-db/Dockerfile
    expose:
      - 3002
    ports:
      - '3002:3002'
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - '.:/project/quiz'

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
      
  quiz-tp:
    container_name: quiz-tp
    build:
      context: .
      dockerfile: ./quiz-tp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - '.:/project/quiz'

  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    container_name: settings
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
